image:
  file: .gitpod.Dockerfile

ports:
  # Laravel server
  - port: 8000
    onOpen: open-preview
  # MySQL server
  - port: 3306
    onOpen: ignore

tasks:
  - init: >
      mysql -u root -e "create database example_app" &&
      composer global require laravel/installer &&
      export PATH="$PATH:$HOME/.composer/vendor/bin" &&
      laravel new workshop &&
      cp composer.json workshop/composer.json &&
      cd workshop &&
      composer install &&
      npm i &&
      cp .env.example .env &&
      sed -i "s|APP_URL=|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env &&
      sed -i "s|APP_URL=https://|APP_URL=https://8000-|g" .env
    command: >
      cd workshop &&
      php artisan key:generate &&
      php -S  127.0.0.1:8000 -t public
  
