image:
  file: .gitpod.Dockerfile

ports:
  # Laravel server
  - port: 8000
    onOpen: open-preview
  # MySQL server
  - port: 3306
    onOpen: ignore

tasks:
  - init: >
      mysql -u root -e "CREATE DATABASE workshop" &&      
      composer global require laravel/installer &&
      export PATH="~/.composer/vendor/bin:$PATH" &&
      laravel new workshop &&
      cp -rT workshop . &&
      rm -R workshop &&      
      cp composer.example composer.json &&
      cp .env.example .env &&
      sed -i "s|APP_URL=http://localhost|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env &&
      sed -i "s|APP_URL=https://|APP_URL=https://8000\-|g" .env &&
      composer update &&
      npm i &&
      php artisan key:generate &&
      php artisan vendor:publish --provider="Competi\CompetiLaravel\Providers\JwtProvider" &&
      sed -i ':a;N;$!ba;s/\* Package Service Providers...\n         \*\//\* Package Service Providers...\n         \*\/\n         Competi\\CompetiLaravel\\Providers\\JwtProvider::class,/g' config/app.php &&
      php artisan jwt:secret &&
      php -S 127.0.0.1:8000 -t public
  - command: >
